function lrpt_prbs_test(symFile)
%LRPT_PRBS_TEST  Is the frame payload a modem test pattern (PRBS)?
%
%   The payload behind the 9-byte frame header is statistically random.
%   Three candidates: compressed imagery, encrypted data, or a PRBS - the
%   pseudo-random bit sequence used to commission radio links. A PRBS is
%   generated by a known LFSR, so its bits satisfy a fixed linear
%   recurrence  b(n) = b(n-m) xor b(n-k)  for the standard (k,m) pairs.
%   Compressed or encrypted data satisfies none of them (~50 % by chance);
%   a true PRBS scores ~(1 - 2*BER)^3 ~ 90 %+ even through our bit errors.
%
%   Tests every standard PRBS polynomial, both tap orders, on the payload
%   bits of the clean frames. A hit closes the case: test transmission,
%   no imagery, with proof.
%
%   USAGE:  lrpt_prbs_test           (picker for the *_sym.mat)
%   Base MATLAB only.

if nargin < 1 || isempty(symFile)
    startDir = 'C:\SDR';
    if ~isfolder(startDir), startDir = pwd; end
    [f, p] = uigetfile({'*.mat', 'lrpt_sync output'}, ...
                       'Pick the symbol file', startDir);
    if isequal(f, 0), fprintf('Cancelled.\n'); return; end
    symFile = fullfile(p, f);
end
S = load(symFile);
fprintf('\n=== lrpt_prbs_test ===\nSymbols: %s\n', S.meta.fname);

NBYTES = 16000;
HOPS   = [ 424 1;  1148 2;  848 2;  1572 3;  2296 4;  1996 4;  2720 5];

% ---------------- chain identical to the other tools --------------------
c  = S.c0;
bI = real(c) < 0;   bQ = imag(c) < 0;
bi = xor(bI(2:end), bI(1:end-1));
bq = xor(bQ(2:end), bQ(1:end-1));
u  = false(2*numel(bi), 1);
u(1:2:end) = bi;  u(2:2:end) = bq;

G1 = [1 1 1 1 0 0 1];  G2 = [1 0 1 1 0 1 1];
asm = '1ACFFC1D';
asmBits = zeros(32,1);
for i = 1:8
    nib = hex2dec(asm(i));
    asmBits(4*i-3:4*i) = bitget(nib, 4:-1:1)';
end
reg = zeros(6,1);  chips = zeros(64,1);
for k = 1:32
    r7 = [asmBits(k); reg];
    chips(2*k-1) = mod(sum(r7 .* G1'), 2);
    chips(2*k)   = mod(sum(r7 .* G2'), 2);
    reg = r7(1:6);
end
tpl = 1 - 2*chips(13:64);
s0  = reg(1)*32 + reg(2)*16 + reg(3)*8 + reg(4)*4 + reg(5)*2 + reg(6);

upm = 1 - 2*double(u);
xc  = filter(flipud(tpl), 1, upm);
pk  = findPeaks(abs(xc), 46);
if sign(median(xc(pk))) < 0, u = ~u; end

outc = zeros(64, 2, 2);
for s = 0:63
    sv = bitget(s, 6:-1:1)';
    for b = 0:1
        r7 = [b; sv];
        outc(s+1, b+1, 1) = mod(sum(r7 .* G1'), 2);
        outc(s+1, b+1, 2) = mod(sum(r7 .* G2'), 2);
    end
end

pnB = ones(8*1300, 1);
for n = 1:numel(pnB)-8
    pnB(n+8) = mod(pnB(n+7) + pnB(n+5) + pnB(n+3) + pnB(n), 2);
end

pkOK = pk(pk + 2*8*(NBYTES+8) <= numel(u));
dens = zeros(size(pkOK));
for i = 1:numel(pkOK)
    dens(i) = sum(abs(pk - pkOK(i) - 8*NBYTES) <= 8*NBYTES);
end
[~, ib] = max(dens);
anchor = pkOK(ib);
rx = double(u(anchor+1 : anchor+2*8*(NBYTES+8)));
db = vdecode(rx, s0, 8*(NBYTES+8), outc);
db = db(1:8*NBYTES);

% walk & collect PAYLOAD BITS (after the 9-byte header) of clean frames
payloads = {};
hs  = 0;
hdr = readHdr(db, hs, pnB);
while true
    bestScore = -1; best = [];
    for hI = 1:size(HOPS,1)
        L = HOPS(hI,1);  st = HOPS(hI,2);
        nh = hs + L;
        if nh + 8 > NBYTES, continue; end
        h2 = readHdr(db, nh, pnB);
        mBits = db(8*(nh-4)+1 : 8*nh);
        aham  = sum(mBits ~= asmBits);
        sc = 2*(aham <= 6) + (h2.ver == 1) + (h2.scid == 0) ...
           + 2*(h2.vcid == 5) + 3*(h2.ctr == hdr.ctr + st) - 0.01*st;
        if sc > bestScore
            bestScore = sc; best = struct('nh',nh,'L',L,'h',h2);
        end
    end
    if isempty(best), break; end
    if ismember(best.L, [424 1148]) && bestScore >= 6
        n = best.L - 4;
        bits = xor(db(8*hs+1 : 8*(hs+n)), pnB(1:8*n));
        payloads{end+1} = bits(8*9+1 : end); %#ok<AGROW>  % skip 9-byte header
    end
    if bestScore < 4, break; end
    hs = best.nh;  hdr = best.h;
end
fprintf('Collected %d clean payloads (%d bits total)\n', ...
        numel(payloads), sum(cellfun(@numel, payloads)));
if numel(payloads) < 2
    fprintf('Not enough clean frames in this window.\n');
    return;
end

% ------------------------------------------------- the PRBS battery
% standard polynomials x^k + x^m + 1 (ITU O.150 + common LFSRs)
POLY = [ 7 6;  9 5;  11 9;  15 14;  17 14;  20 3;  20 17;  23 18; ...
         23 5;  29 27;  31 28];
fprintf('\n%-12s %-10s %s\n', 'PRBS', 'match %', '(50% = not this PRBS; >85% = HIT)');
bestHit = 0; bestName = '';
for pi2 = 1:size(POLY,1)
    k = POLY(pi2,1);  m = POLY(pi2,2);
    for ord = 1:2
        if ord == 2, mm = k - m; else, mm = m; end
        tot = 0; hit = 0;
        for fi2 = 1:numel(payloads)
            b = payloads{fi2};
            if numel(b) <= k, continue; end
            pred = xor(b(k-mm+1 : end-mm), b(1 : end-k));
            hit = hit + sum(b(k+1:end) == pred);
            tot = tot + numel(b) - k;
        end
        pct = 100*hit/max(tot,1);
        fprintf('PRBS%-2d(%2d,%2d) %6.1f %%\n', k, k, mm, pct);
        dev = max(pct, 100-pct);
        if dev > bestHit, bestHit = dev; bestName = sprintf('PRBS%d(%d,%d)', k, k, mm); end
    end
end

fprintf('\n--- VERDICT ---\n');
if bestHit >= 85
    fprintf('%s FITS at %.1f %%: the payload is a MODEM TEST PATTERN.\n', bestName, bestHit);
    fprintf('The satellite is commissioning its transmitter - there is no\n');
    fprintf('imagery in this signal, and that is now proven at the bit level.\n');
elseif bestHit >= 65
    fprintf('Partial fit (%s at %.1f %%) - suspicious, look closer.\n', bestName, bestHit);
else
    fprintf('NO standard PRBS fits (best %.1f %%). The payload is compressed\n', bestHit);
    fprintf('or encrypted data - structure exists but not a test pattern.\n');
    fprintf('If compressed imagery, only the operator''s ground software (or\n');
    fprintf('crypto keys) can open it. The reverse-engineering ends here with\n');
    fprintf('a fully mapped link layer and an unknown payload codec.\n');
end
end

% ------------------------------------------------------------------------
function h = readHdr(db, off, pnB)
bits = xor(db(8*off+1 : 8*off+48), pnB(1:48));
by = packBytes(bits);
h.ver  = floor(by(1)/64);
h.scid = mod(by(1),64)*4 + floor(by(2)/64);
h.vcid = mod(by(2), 64);
h.ctr  = by(3)*65536 + by(4)*256 + by(5);
h.sig  = by(6);
end

function bitsOut = vdecode(rx, s0, nBits, outc)
PM = inf(64,1);  PM(s0+1) = 0;
prev = zeros(64, nBits, 'uint8');
ns   = (0:63)';
bvec = floor(ns/32);
sA   = 2*mod(ns,32) + 1;
sB   = sA + 1;
liA  = sA + 64*bvec;
liB  = sB + 64*bvec;
o1 = squeeze(outc(:,:,1));  o2 = squeeze(outc(:,:,2));
for t = 1:nBits
    cost = double(o1 ~= rx(2*t-1)) + double(o2 ~= rx(2*t));
    cand = PM + cost;
    mA = cand(liA);  mB = cand(liB);
    takeB = mB < mA;
    PMn = mA;  PMn(takeB) = mB(takeB);
    pS  = sA;  pS(takeB) = sB(takeB);
    prev(:, t) = uint8(pS - 1);
    PM = PMn;
end
[~, sEnd] = min(PM);
s = sEnd - 1;
bitsOut = zeros(nBits, 1);
for t = nBits:-1:1
    bitsOut(t) = floor(s/32);
    s = double(prev(s+1, t));
end
end

function by = packBytes(bits)
n  = floor(numel(bits)/8);
by = bits(1:8:8*n)*128 + bits(2:8:8*n)*64 + bits(3:8:8*n)*32 + ...
     bits(4:8:8*n)*16  + bits(5:8:8*n)*8  + bits(6:8:8*n)*4 + ...
     bits(7:8:8*n)*2   + bits(8:8:8*n);
end

function pk = findPeaks(a, thr)
idx = find(a >= thr);
pk = [];
while ~isempty(idx)
    grp = idx(idx <= idx(1) + 8);
    [~, gi] = max(a(grp));
    pk(end+1,1) = grp(gi); %#ok<AGROW>
    idx(idx <= grp(end) + 8) = [];
end
end
