function necpath = qfh_write_nec(geom, design, params, necpath)
%QFH_WRITE_NEC Exports the geometry in NEC2 format (.nec) for 4nec2.
%
%   necpath = QFH_WRITE_NEC(geom, design, params)            - default name
%   necpath = QFH_WRITE_NEC(geom, design, params, 'out.nec') - given name
%
%   The generated cards have the same format as those produced by
%   QFH2nec.c (https://github.com/oceantrotter/QFH2nec):
%     CM/CE - comments               GW - wires (coordinates in METERS)
%     GE    - end of geometry        FR - frequency sweep
%     EX    - excitation (voltage source on the feed wire)
%     RP    - radiation pattern      EN - end of file

if nargin < 4 || isempty(necpath)
    necpath = sprintf('QFH_%.1fMHz.nec', params.freq_mhz);
end

nfo = design.info;
fid = fopen(necpath, 'w');
if fid < 0
    error('qfh:io', 'Cannot write file %s', necpath);
end

fprintf(fid, 'CM QFH antenna - generated by qfh_matlab (MATLAB port of QFH2nec / Coppens calc.)\n');
fprintf(fid, 'CM target f=%.3f MHz (freq_cal=%.4f -> design f=%.3f MHz)\n', ...
        params.freq_mhz, params.freq_cal, design.f_design_mhz);
fprintf(fid, 'CM turns=%.2f  1 turn=%.2f lambda  W/H=%.2f  %s\n', ...
        params.turns, params.turn_len_wl, params.ratio, upper(params.polarity));
fprintf(fid, 'CM bend radius=%.1f mm  wire diameter=%.2f mm\n', ...
        params.bend_r_mm, params.wire_d_mm);
fprintf(fid, 'CM small loop: H=%.1f D=%.1f mm | large loop: H=%.1f D=%.1f mm\n', ...
        design.loops(1).H, design.loops(1).D, design.loops(2).H, design.loops(2).D);
fprintf(fid, 'CM sweep %.3f - %.3f MHz, step %.3f MHz\n', ...
        params.f_start, params.f_stop, params.f_step);
fprintf(fid, 'CE\n');

% GW: tag nseg x1 y1 z1 x2 y2 z2 radius    (all coordinates in METERS)
for t = 1:numel(geom.wires)
    w = geom.wires(t);
    fprintf(fid, 'GW %d %d %.5E %.5E %.5E %.5E %.5E %.5E %.5E\n', ...
            t, w.nseg, ...
            w.p1(1)/1000, w.p1(2)/1000, w.p1(3)/1000, ...
            w.p2(1)/1000, w.p2(2)/1000, w.p2(3)/1000, ...
            w.r/1000);
end

fprintf(fid, 'GE 0\n');                    % free space (no ground)

nfr = floor((params.f_stop - params.f_start)/params.f_step + 1e-9) + 1;
fprintf(fid, 'FR 0 %d 0 0 %.5E %.5E\n', nfr, params.f_start, params.f_step);

% excitation: voltage source on segment 1 of the feed wire
fprintf(fid, 'EX 0 %d 1 0 1.00000E+00 0.00000E+00\n', geom.feed_idx);

% radiation pattern: 37 x 37 points, 5 (theta) and 10 (phi) degree steps
fprintf(fid, 'RP 0 37 37 1000 0.00000E+00 0.00000E+00 5.00000E+00 1.00000E+01 0.00000E+00 0.00000E+00\n');
fprintf(fid, 'EN\n');
fclose(fid);

% ----- summary + sanity checks for the NEC model -----
wr     = [geom.wires.r];
nseg   = [geom.wires.nseg];
lens   = arrayfun(@(w) norm(w.p2 - w.p1), geom.wires);
perseg = lens ./ nseg;

fprintf('\nNEC file written: %s\n', necpath);
fprintf('  wires (GW): %d | total segments: %d\n', numel(geom.wires), sum(nseg));
fprintf('  segment length: min %.1f mm, max %.1f mm (recommended < lambda/10 = %.0f mm)\n', ...
        min(perseg), max(perseg), nfo.wavel/10);

if max(perseg) > nfo.wavel/10
    warning('qfh:seg', ...
        'Some segments are longer than lambda/10 - increase seg_helix / seg_radial.');
end
% NEC-2 thin-wire kernel guideline: segment length >= 8 x wire radius;
% below 2 x radius the results become genuinely unreliable without the
% extended kernel
nbad  = sum(perseg < 2*wr);
nwarn = sum(perseg >= 2*wr & perseg < 8*wr);
if nbad > 0
    warning('qfh:seg', ...
        ['%d segments are shorter than 2 x the wire radius - NEC results are ' ...
         'not trustworthy like this. Increase bend_r_mm / decrease seg_corner, ' ...
         'or enable the extended kernel in 4nec2 (Settings > Use extended thin-wire kernel).'], nbad);
elseif nwarn > 0
    fprintf(['  note: %d segments below 8 x the wire radius (NEC-2 guideline). For maximum ' ...
             'accuracy enable the extended kernel in 4nec2 (Settings) or decrease seg_corner.\n'], nwarn);
end
end
