function qfh_write_template(marks, params, pdffile)
%QFH_WRITE_TEMPLATE Real-scale (1:1) A4 mast-drilling template as a PDF.
%
%   QFH_WRITE_TEMPLATE(marks, params, 'QFH_drill_template.pdf')
%
%   CREDIT: the page layout is inspired by the printable template of the
%   ON6JC/LW3HAZ QFH design tool by John Coppens
%   (https://www.jcoppens.com/ant/qfh). Full credit to him for the
%   concept - this is an independent MATLAB implementation driven by the
%   qfh_matlab geometry.
%
%   The page contains three wrap-around strips (TOP / MIDDLE / BOTTOM).
%   Each strip is exactly one mast circumference long in the wrap
%   direction (1:1), and true-scale in the axial direction inside the
%   strip, so every hole lands at its exact angle and relative depth.
%   NOTE on orientation: within a strip the depth axis grows toward the
%   printed LEFT (mirrored on purpose) - wrapping printed-side-out with
%   angles increasing counter-clockwise (seen from the top) maps the
%   printed right side UP the mast, so only the mirrored layout puts
%   deeper stations lower, where they belong.
%   Hole circles are drawn at their REAL diameters (wire holes at the
%   top/bottom, support-tube holes at the middle). The absolute depth of
%   each station is listed in the table and is measured with a ruler
%   along the seam line. A 100 mm calibration bar detects printer
%   scaling. The PDF is generated directly by MATLAB (vector graphics,
%   exact A4) - no browser or external tool involved.

C = pi * params.mast_d_mm;              % mast circumference [mm]
if C > 150
    error('qfh:template', ...
        'Mast circumference %.0f mm does not fit the A4 strip area (max ~150 mm).', C);
end

% --- figure set up so that 1 data unit = 1 mm on paper ---
% The on-screen figure size MUST equal the paper size: with
% PaperPositionMode='manual' MATLAB scales the drawn figure onto the
% paper rectangle, and any size mismatch would scale the two axes
% differently (circles would print as ellipses, the layout would
% overflow the page).
fig = figure('Visible', 'off', 'Color', 'w', 'InvertHardcopy', 'off', ...
             'Units', 'centimeters', 'Position', [0 0 21 29.7]);
set(fig, 'PaperUnits', 'centimeters', 'PaperType', 'a4', ...
         'PaperPositionMode', 'manual', 'PaperSize', [21 29.7], ...
         'PaperPosition', [0 0 21 29.7]);
ax = axes(fig, 'Units', 'centimeters', 'Position', [1.5 1.5 18 26.4], ...
          'XLim', [0 180], 'YLim', [0 264], 'YDir', 'normal', 'Visible', 'off');
hold(ax, 'on');

% ------------------------------ header ----------------------------------
text(ax, 0, 262, sprintf('QFH mast drilling template  -  target %.3f MHz', ...
     params.freq_mhz), 'FontSize', 12, 'FontWeight', 'bold', 'VerticalAlignment', 'top');
text(ax, 0, 256, ['Layout inspired by the ON6JC/LW3HAZ QFH design tool by ' ...
     'John Coppens - jcoppens.com/ant/qfh'], ...
     'FontSize', 8, 'FontAngle', 'italic', 'VerticalAlignment', 'top');
text(ax, 0, 251.5, sprintf(['Mast dia. %.1f mm (circumference %.1f mm)  |  ' ...
     'support tube dia. %.1f mm  |  wire dia. %.2f mm  |  generated by qfh_matlab'], ...
     params.mast_d_mm, C, params.support_d_mm, params.wire_d_mm), ...
     'FontSize', 8, 'VerticalAlignment', 'top', 'Interpreter', 'none');

instr = { ...
 '1. Print at 100% / "Actual size" (never "fit to page"). Check: the calibration bar below must measure exactly 100.0 mm.', ...
 '2. Draw a straight SEAM line along the mast. On it, mark the depth of every station (table below), measured from the antenna top plane (depth 0 = feed level).', ...
 '3. Cut out each strip and wrap it around the mast, printed side out: 0-deg edge on the seam, station line(s) on the matching depth mark(s). The strip ends must meet on the seam.', ...
 '4. WRAP DIRECTION MATTERS: seen from the TOP of the mast, angles must increase counter-clockwise. Wrapping the other way mirrors the antenna (LHCP instead of RHCP!).', ...
 '5. SANITY CHECK after wrapping: deeper station lines must sit LOWER on the mast (large-loop middle below small-loop middle). If inverted, the strip is wrapped the wrong way.', ...
 sprintf('6. Drill through the center of every circle: small circles = wire holes (dia. %.2f mm), large circles = support-tube holes (dia. %.1f mm).', params.wire_d_mm, params.support_d_mm), ...
 '7. Equal letters = same helix arm (A/B = small loop, C/D = large loop).'};
for i = 1:numel(instr)
    text(ax, 0, 246 - 3.5*(i-1), instr{i}, 'FontSize', 7, 'VerticalAlignment', 'top');
end

% -------------------------- calibration bar -----------------------------
yc = 219;
plot(ax, [0 100], [yc yc], 'k-', 'LineWidth', 1);
plot(ax, [0 0], yc + [-2 2], 'k-', 'LineWidth', 1);
plot(ax, [100 100], yc + [-2 2], 'k-', 'LineWidth', 1);
text(ax, 102, yc, '100.0 mm calibration bar', 'FontSize', 7, 'VerticalAlignment', 'middle');

% ------------------------------ strips ----------------------------------
posOrder = {'top', 'middle', 'bottom'};
gname    = {'TOP', 'MIDDLE', 'BOTTOM'};
ysTop    = 206;                    % top edge of the strips
margin   = 10;                     % axial margin inside a strip [mm]
xcur     = 6;
stripGap = 11;

% global station numbering by depth (marks are sorted by depth)
depths = [marks.depth_mm];

for g = 1:3
    idx = find(strcmp({marks.position}, posOrder{g}));
    dmin = min(depths(idx));  dmax = max(depths(idx));
    w = (dmax - dmin) + 2*margin;
    x0 = xcur;  y0 = ysTop - C;

    rectangle(ax, 'Position', [x0, y0, w, C], 'EdgeColor', 'k', 'LineWidth', 0.8);
    text(ax, x0 + w/2, ysTop + 9, gname{g}, 'FontSize', 9, 'FontWeight', 'bold', ...
         'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom');

    % angle ticks every 30 deg, labels every 90 deg (0 deg = strip top edge)
    for aa = 0:30:360
        yt = ysTop - aa/360*C;
        plot(ax, [x0, x0 + 2], [yt yt], 'k-', 'LineWidth', 0.4);
        plot(ax, [x0 + w - 2, x0 + w], [yt yt], 'k-', 'LineWidth', 0.4);
        if mod(aa, 90) == 0
            text(ax, x0 - 1, yt, sprintf('%d', aa), 'FontSize', 6, ...
                 'HorizontalAlignment', 'right', 'VerticalAlignment', 'middle');
        end
    end

    for m = idx
        % AXIAL MIRROR - do not "simplify" this back to (depth - dmin)!
        % When the strip is wrapped printed-side OUT with angles
        % increasing counter-clockwise (seen from the top of the mast),
        % the printed RIGHT side of the strip points UP the mast. So the
        % depth axis must grow toward the printed LEFT for the station
        % lines to land on their seam marks in the correct order
        % (deeper = lower on the mast). Verified by wrapping a printed
        % sheet - drawing it the intuitive way inverts the stations.
        xs = x0 + margin + (dmax - marks(m).depth_mm);
        plot(ax, [xs xs], [y0, ysTop], '--', 'Color', [0.45 0.45 0.45], 'LineWidth', 0.4);
        stno = find(sort(unique(depths)) == marks(m).depth_mm, 1);
        text(ax, xs, y0 - 1, sprintf('st.%d', stno), 'FontSize', 6, ...
             'HorizontalAlignment', 'center', 'VerticalAlignment', 'top');

        r0 = marks(m).hole_d_mm / 2;
        for j = 1:2
            ang = marks(m).angles_deg(j);
            yy = ysTop - ang/360*C;
            drawhole(ax, xs, yy, r0, marks(m).arms{j}, ang);
            % a hole touching the seam is drawn at both strip edges
            % (the two ends meet there when the strip is wrapped)
            margdeg = r0/C*360 + 1e-9;
            if ang < margdeg
                drawhole(ax, xs, yy - C, r0, marks(m).arms{j}, ang);
            elseif ang > 360 - margdeg
                drawhole(ax, xs, yy + C, r0, marks(m).arms{j}, ang);
            end
        end
    end

    xcur = xcur + w + stripGap;
end

% ------------------------------- table ----------------------------------
yT = 92;
text(ax, 0, yT, 'st.  loop    position   depth [mm]   hole dia. [mm]   angles [deg]     arms', ...
     'FontSize', 7.5, 'FontName', 'Courier', 'FontWeight', 'bold', 'VerticalAlignment', 'top');
for i = 1:numel(marks)
    m = marks(i);
    stno = find(sort(unique(depths)) == m.depth_mm, 1);
    text(ax, 0, yT - 4*i, sprintf('%-4d %-7s %-10s %8.1f %14.2f     %5.1f / %5.1f    %s / %s', ...
         stno, m.loop, m.position, m.depth_mm, m.hole_d_mm, ...
         m.angles_deg(1), m.angles_deg(2), m.arms{1}, m.arms{2}), ...
         'FontSize', 7.5, 'FontName', 'Courier', 'VerticalAlignment', 'top');
end
text(ax, 0, yT - 4*numel(marks) - 6, ...
     ['Depths are to HOLE CENTERS, measured from the antenna top plane. ' ...
      'Angles: 0 deg = seam line, increasing counter-clockwise seen from the top.'], ...
     'FontSize', 7, 'FontAngle', 'italic', 'VerticalAlignment', 'top');

% ------------------------------- output ---------------------------------
print(fig, pdffile, '-dpdf', '-r600');
[pp, nn] = fileparts(pdffile);
pngfile = fullfile(pp, [nn '_preview.png']);
print(fig, pngfile, '-dpng', '-r150');
close(fig);

fprintf('\nDrilling template written: %s (1 A4 page, 1:1 scale)\n', pdffile);
fprintf('Preview image: %s\n', pngfile);
fprintf('Print at 100%% / "Actual size" and verify the 100 mm calibration bar!\n');
end

% =========================================================================
function drawhole(ax, x, y, r0, armlabel, ang)
rectangle(ax, 'Position', [x - r0, y - r0, 2*r0, 2*r0], 'Curvature', [1 1], ...
          'EdgeColor', [0.85 0 0], 'LineWidth', 0.8);
plot(ax, x + [-(r0 + 1.5), r0 + 1.5], [y y], '-', 'Color', [0.85 0 0], 'LineWidth', 0.3);
plot(ax, [x x], y + [-(r0 + 1.5), r0 + 1.5], '-', 'Color', [0.85 0 0], 'LineWidth', 0.3);
text(ax, x + r0 + 2, y, sprintf('%s %.1f', armlabel, ang), 'FontSize', 6, ...
     'Color', [0.85 0 0], 'VerticalAlignment', 'middle');
end
